version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/ACC_Backup1

permissions:
  - object: /home/ubuntu/ACC_Backup1
    pattern: "*"
    owner: ubuntu
    group: ubuntu

hooks:
  # BeforeInstall:
  #   - location: /home/ubuntu/ACC_Backup/scripts/before_install.sh
  #     timeout: 1000
  #     runas: root
  
  # AfterInstall:
  #   - location: /home/ubuntu/ACC_Backup/scripts/after_install.sh
  #     timeout: 1500
  #     runas: root

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 301
      runas: root